"""empty message

Revision ID: 554a92410f37
Revises: 
Create Date: 2020-06-03 07:59:41.786386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554a92410f37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('end', sa.Date(), nullable=True))
    op.add_column('schedule', sa.Column('start', sa.Date(), nullable=True))
    op.drop_column('schedule', 'end_time')
    op.drop_column('schedule', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('end_time', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('schedule', 'start')
    op.drop_column('schedule', 'end')
    # ### end Alembic commands ###
